#ifndef ZEPHYR_SOC_MICROCHIP_PIC32CM_LS00_H_
#define ZEPHYR_SOC_MICROCHIP_PIC32CM_LS00_H_
#ifndef _ASMLANGUAGE
#include <zephyr/types.h>
/* CMSIS device feature definitions */
#define __NVIC_PRIO_BITS 2U
#define __MPU_PRESENT    1U
#define __VTOR_PRESENT   1U
#define __FPU_PRESENT    0U
#if defined(CONFIG_SOC_PIC32CM5164LS00048)
#include <pic32cm5164ls00048.h>
#include <port.h>
#else
#error "Library does not support the specified device."
#endif



/* Generic IRQ table placeholder - vendor HAL pack does not yet ship one. */
typedef enum {
	Reset_IRQn            = -15,
	NonMaskableInt_IRQn   = -14,
	HardFault_IRQn        = -13,
	SVCall_IRQn           =  -5,
	DebugMonitor_IRQn     =  -4,
	PendSV_IRQn           =  -2,
	SysTick_IRQn          =  -1,
	PERIPH0_IRQn = 0, PERIPH1_IRQn, PERIPH2_IRQn, PERIPH3_IRQn, PERIPH4_IRQn,
	PERIPH5_IRQn, PERIPH6_IRQn, PERIPH7_IRQn, PERIPH8_IRQn, PERIPH9_IRQn,
	PERIPH10_IRQn, PERIPH11_IRQn, PERIPH12_IRQn, PERIPH13_IRQn, PERIPH14_IRQn,
	PERIPH15_IRQn, PERIPH16_IRQn, PERIPH17_IRQn, PERIPH18_IRQn, PERIPH19_IRQn,
	PERIPH20_IRQn, PERIPH21_IRQn, PERIPH22_IRQn, PERIPH23_IRQn, PERIPH24_IRQn,
	PERIPH25_IRQn, PERIPH26_IRQn, PERIPH27_IRQn, PERIPH28_IRQn, PERIPH29_IRQn,
	PERIPH30_IRQn, PERIPH31_IRQn, PERIPH32_IRQn, PERIPH33_IRQn, PERIPH34_IRQn,
	PERIPH35_IRQn, PERIPH36_IRQn, PERIPH37_IRQn, PERIPH38_IRQn, PERIPH39_IRQn,
	PERIPH40_IRQn, PERIPH41_IRQn, PERIPH42_IRQn, PERIPH43_IRQn, PERIPH44_IRQn,
	PERIPH45_IRQn, PERIPH46_IRQn, PERIPH47_IRQn, PERIPH48_IRQn, PERIPH49_IRQn,
	PERIPH50_IRQn, PERIPH51_IRQn, PERIPH52_IRQn, PERIPH53_IRQn, PERIPH54_IRQn,
	PERIPH55_IRQn, PERIPH56_IRQn, PERIPH57_IRQn, PERIPH58_IRQn, PERIPH59_IRQn,
	PERIPH60_IRQn, PERIPH61_IRQn, PERIPH62_IRQn, PERIPH63_IRQn, PERIPH64_IRQn,
	PERIPH65_IRQn, PERIPH66_IRQn, PERIPH67_IRQn, PERIPH68_IRQn, PERIPH69_IRQn,
	PERIPH70_IRQn,
} IRQn_Type;

#include <cmsis_core_m_defaults.h>

#endif /* _ASMLANGUAGE */
#endif /* ZEPHYR_SOC_MICROCHIP_PIC32CM_LS00_H_ */
