/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DTS_BINDINGS_PIC32C_PIC32CM_LS_COMMON_MCHP_PINCTRL_PINMUX_PIC32C_H
#define ZEPHYR_DTS_BINDINGS_PIC32C_PIC32CM_LS_COMMON_MCHP_PINCTRL_PINMUX_PIC32C_H

#define MCHP_PINMUX(pin, mux) \
	(((pin) << 16) | (mux))

/* Peripheral mux values */
#define MCHP_PINMUX_FUNC_A	0
#define MCHP_PINMUX_FUNC_B	1
#define MCHP_PINMUX_FUNC_C	2
#define MCHP_PINMUX_FUNC_D	3
#define MCHP_PINMUX_FUNC_E	4
#define MCHP_PINMUX_FUNC_F	5
#define MCHP_PINMUX_FUNC_G	6
#define MCHP_PINMUX_FUNC_H	7
#define MCHP_PINMUX_FUNC_I	8
#define MCHP_PINMUX_FUNC_K	10
#define MCHP_PINMUX_FUNC_P	15

/* Pin definitions */
#define MCHP_PIN_PA04	4
#define MCHP_PIN_PA05	5
#define MCHP_PIN_PA08	8
#define MCHP_PIN_PA09	9
#define MCHP_PIN_PA16	16
#define MCHP_PIN_PA17	17
#define MCHP_PIN_PB03	35

/* SERCOM0 */
#define MCHP_PINMUX_PA04_SERCOM0_PAD0 \
	MCHP_PINMUX(MCHP_PIN_PA04, MCHP_PINMUX_FUNC_D)

#define MCHP_PINMUX_PA05_SERCOM0_PAD1 \
	MCHP_PINMUX(MCHP_PIN_PA05, MCHP_PINMUX_FUNC_D)

#define MCHP_PINMUX_PA08_SERCOM0_PAD0 \
	MCHP_PINMUX(MCHP_PIN_PA08, MCHP_PINMUX_FUNC_D)

#define MCHP_PINMUX_PA09_SERCOM0_PAD1 \
	MCHP_PINMUX(MCHP_PIN_PA09, MCHP_PINMUX_FUNC_D)

/* SERCOM1 */
#define MCHP_PINMUX_PA16_SERCOM1_PAD0 \
	MCHP_PINMUX(MCHP_PIN_PA16, MCHP_PINMUX_FUNC_C)

#define MCHP_PINMUX_PA17_SERCOM1_PAD1 \
	MCHP_PINMUX(MCHP_PIN_PA17, MCHP_PINMUX_FUNC_C)

/* TC0 */
#define MCHP_PINMUX_PA04_TC0_WO0 \
	MCHP_PINMUX(MCHP_PIN_PA04, MCHP_PINMUX_FUNC_E)

/* EIC */
#define MCHP_PINMUX_PB03_EIC_EXTINT3 \
	MCHP_PINMUX(MCHP_PIN_PB03, MCHP_PINMUX_FUNC_A)

#endif

